name: Asana Git
uses: insurify/github-asana-action@v2.0.0
description: 'Asana Github Actions'
inputs:
  asana-pat:
    description: '1/1188114868548560:67e8e0815543662b8571fd106affa645'
    required: true
  task-comment:
    description: 'Pull Request created'
    required: false
  targets: '[{"project": "Baba iron and cement store", "section": "Done"}, {"project": "Current Sprint", "section": "In Review"}]'
  trigger-phrase:
    description: 'https://app.asana.com/'
    required: true
branding:
  icon: 'chevron-right'
  color: 'gray-dark'
runs:
  using: 'python3.6'
  main: 'manage.py'