- name: Asana Github Actions
  uses: everphone-gmbh/github-asana-action@385529c

inputs:
  asana-pat:
    description: '1/1188114868548560:fe041f6047b1b9de259c8c4b78968c63'
    required: true
  task-comment:
    description: 'Pull Request created'
    required: false
  targets: '[{"project": "Baba iron and cement store", "section": "Done"}, {"project": "Current Sprint", "section": "In Review"}]'
  trigger-phrase:
    description: 'https://app.asana.com/'
    required: true
branding:
  icon: 'chevron-right'
  color: 'gray-dark'
runs:
  using: 'python3.6'
  main: 'manage.py'